### ISSUE TITLE
what the fuck

### ISSUE THREAD

**Issue by oodrand** [AvianJay/useless-script#1]
why does bigfilemaker spam the file with %random%???????????????? fill it with zeros!

**Comment by AvianJay** [comment]
> why does bigfilemaker spam the file with %random%???????????????? fill it with zeros!

bruh idk why i put %random% in it

Honestly, I never thought anyone would watch this.

**Comment by AvianJay** [comment]
I got it done

**Comment by oodrand** [comment]
nice work
